### ISSUE TITLE
Module oracle_sqldba with catcon_pl in an Python 3.6 environment.

### ISSUE THREAD

**Issue by aliensmily** [oravirt/ansible-oracle#334]
Hi,

i seems module oracle_sqldba got a bug, when it is used with catcon_pl in an Python 3.6 environment.
Is there a required Python3 Version?

One sample Task that will raise the error:
```
  - name: utltz_upg_check.sql - CDB/SingleInstance
    opitzconsulting.ansible_oracle.oracle_sqldba:
      catcon_pl: "{{ ora_home.home_path }}/rdbms/admin/utltz_upg_check.sql"
      scope: cdb
      oracle_home: "{{ ora_home.home_path }}"
      oracle_db_name: "{{ ora_instance.SID }}"
```

We got the following error
```
TASK [oracle_db_timezone_upgrade : utltz_upg_check.sql - CDB/SingleInstance] **********************************************************************************************
task path: /home/oracle/database_ansible/roles/oracle_db_timezone_upgrade/tasks/timezone_upg.yml:68
The full traceback is:
Traceback (most recent call last):
  File "/var/tmp/ansible-tmp-1678178858.8904803-2370422-47530891410840/AnsiballZ_oracle_sqldba", line 107, in <module>
    _ansiballz_main()
  File "/var/tmp/ansible-tmp-1678178858.8904803-2370422-47530891410840/AnsiballZ_oracle_sqldba", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/tmp/ansible-tmp-1678178858.8904803-2370422-47530891410840/AnsiballZ_oracle_sqldba", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload_2dg3i_yg/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload.zip/ansible/modules/opitzconsulting/ansible_oracle/oracle_sqldba.py", line 445, in <module>
  File "/tmp/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload_2dg3i_yg/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload.zip/ansible/modules/opitzconsulting/ansible_oracle/oracle_sqldba.py", line 432, in main
  File "/tmp/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload_2dg3i_yg/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload.zip/ansible/modules/opitzconsulting/ansible_oracle/oracle_sqldba.py", line 337, in run_catcon_pl
TypeError: must be str, not bytes
fatal: [somehostname.domain.com]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to somehostname.domain.com closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/var/tmp/ansible-tmp-1678178858.8904803-2370422-47530891410840/AnsiballZ_oracle_sqldba\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/var/tmp/ansible-tmp-1678178858.8904803-2370422-47530891410840/AnsiballZ_oracle_sqldba\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/var/tmp/ansible-tmp-1678178858.8904803-2370422-47530891410840/AnsiballZ_oracle_sqldba\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload_2dg3i_yg/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload.zip/ansible/modules/opitzconsulting/ansible_oracle/oracle_sqldba.py\", line 445, in <module>\r\n  File \"/tmp/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload_2dg3i_yg/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload.zip/ansible/modules/opitzconsulting/ansible_oracle/oracle_sqldba.py\", line 432, in main\r\n  File \"/tmp/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload_2dg3i_yg/ansible_opitzconsulting.ansible_oracle.oracle_sqldba_payload.zip/ansible/modules/opitzconsulting/ansible_oracle/oracle_sqldba.py\", line 337, in run_catcon_pl\r\nTypeError: must be str, not bytes\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

When we adjust the code of module oracle_sqldba a bit it worked in our environment (see attached).
We added some decode/encoding stuff. 
[oracle_sqldba.zip](https://github.com/oravirt/ansible-oracle/files/10907903/oracle_sqldba.zip)

ps: format changes

**Comment by Rendanic** [comment]
What OS + Version are you using?

**Comment by aliensmily** [comment]
RHEL8 + ansible [core 2.13.3]

**Comment by Rendanic** [comment]
Looks like a known bug in `ansible-oracle-modules` when using Python3.
Maybe similar to #287 and #255

**Comment by aliensmily** [comment]
sorry, forget to mention, we are on module version 3.5.1 of opitzconsulting.ansible_oracle
